import type { LemonCatalogProduct } from "./products";

// Generated by `pnpm sync:products`.
// Do not edit this file directly. Edit Lemon Squeezy product data or `productOverrides.ts`.
export const lemonCatalogProducts = [
  {
    slug: "manifest-wealth-and-success-5088fda5-c0ab-4aba-bb59-7d721c148245",
    title: "Manifest Wealth and Success",
    description: "",
    priceCents: 999,
    currency: "GBP",
    lemonSqueezy: {
      productId: "1202798",
      variantId: "1880232",
      buyNowUrl: "https://yourpreferredlife.lemonsqueezy.com/checkout/buy/5088fda5-c0ab-4aba-bb59-7d721c148245",
      productStatus: "published",
      variantStatus: "pending",
      testMode: true
    }
  }
] satisfies LemonCatalogProduct[];
